import 'themes_data/themes_data.dart';

enum AppTheme {
  initial,
  winterfell,
  dorne,
  kingsLanding,
  beyondTheWall,
  highgarden,
  yunkai,
  dragonstone,
  dothrakiSea,
  redMountains,
  volantis,
  kingsroad,
  qarth,
  pyke,
  meereen,
  ironIslands,
  braavos,
  casterlyRock,
}

final appThemeData = {
  AppTheme.initial: initialThemeData,
  AppTheme.dorne: dorneThemeData,
  AppTheme.winterfell: winterfellThemeData,
  AppTheme.kingsLanding: kingsLandingThemeData,
  AppTheme.beyondTheWall: beyondTheWallThemeData,
  AppTheme.highgarden: highgardenThemeData,
  AppTheme.yunkai: yunkaiThemeData,
  AppTheme.dragonstone: dragonstoneThemeData,
  AppTheme.dothrakiSea: dothrakiSeaThemeData,
  AppTheme.redMountains: redMountainsThemeData,
  AppTheme.volantis: volantisThemeData,
  AppTheme.kingsroad: kingsroadThemeData,
  AppTheme.qarth: qarthThemeData,
  AppTheme.pyke: pykeThemeData,
  AppTheme.meereen: meereenThemeData,
  AppTheme.ironIslands: ironIslandsThemeData,
  AppTheme.braavos: braavosThemeData,
};
